spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/user_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
